name:                dailycode-haskell
version:             0.1.0.0
github:              "rmullin7286/dailycode-haskell"
license:             GPL-3
author:              "Ryan Mullin"
maintainer:          "ryan.mullin12@gmail.com"
copyright:           "2021 Ryan Mullin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rmullin7286/dailycode-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.5.1
- mtl >= 2.2.2
- vector >= 0.12.3.1
- random >= 1.2.1

executables:
  prefix-map-sum:
    main: Main.hs
    source-dirs: prefix_map_sum
  partition_sum_minimized:
    main: Main.hs
    source-dirs: partition_sum_minimized
  h_index:
    main: Main.hs
    source-dirs: h_index
  ghost_game:
    main: Main.hs
    source-dirs: ghost_game
  boustrophedon:
    main: Main.hs
    source-dirs: boustrophedon
  relative_sequence:
    main: Main.hs
    source-dirs: relative_sequence
  fixed_point:
    main: Main.hs
    source-dirs: fixed_point
  site_similarity:
    main: Main.hs
    source-dirs: site_similarity
  celebrity_problem:
    main: Main.hs
    source-dirs: celebrity_problem
  minimum_perfect_squares:
    main: Main.hs
    source-dirs: minimum_perfect_squares
  manhattan_distance:
    main: Main.hs
    source-dirs: manhattan_distance
  index_value_equality:
    main: Main.hs
    source-dirs: index_value_equality
  merge_trees:
    main: Main.hs
    source-dirs: merge_trees
  nth_perfect_number:
    main: Main.hs
    source-dirs: nth_perfect_number
  pascals_triangle:
    main: Main.hs
    source-dirs: pascals_triangle
# executables:
#   dailycode-haskell-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - dailycode-haskell

